export const DEL_INTERN_COMMENT_INIT = 'DEL_INTERN_COMMENT_INIT';
export const DEL_INTERN_COMMENT_SUCCESS = 'DEL_INTERN_COMMENT_SUCCESS';
export const DEL_INTERN_COMMENT_ERROR = 'DEL_INTERN_COMMENT_ERROR';
export const DEL_INTERN_COMMENT_RESET = 'DEL_INTERN_COMMENT_RESET';

export const ADD_INTERN_COMMENT_INIT = 'ADD_INTERN_COMMENT_INIT';
export const ADD_INTERN_COMMENT_SUCCESS = 'ADD_INTERN_COMMENT_SUCCESS';
export const ADD_INTERN_COMMENT_RESET = 'ADD_INTERN_COMMENT_RESET';
export const ADD_INTERN_COMMENT_ERROR = 'ADD_INTERN_COMMENT_ERROR';

export const SET_INTERN_COMMENT_LIKE_INIT = 'SET_INTERN_COMMENT_LIKE_INIT';
export const SET_INTERN_COMMENT_LIKE_SUCCESS = 'SET_INTERN_COMMENT_LIKE_SUCCESS';
export const SET_INTERN_COMMENT_LIKE_RESET = 'SET_INTERN_COMMENT_LIKE_RESET';
export const SET_INTERN_COMMENT_LIKE_ERROR = 'SET_INTERN_COMMENT_LIKE_ERROR';

export const GET_INTERN_COMMENT_INIT = 'GET_INTERN_COMMENT_INIT';
export const GET_INTERN_COMMENT_SUCCESS = 'GET_INTERN_COMMENT_SUCCESS';
export const GET_INTERN_COMMENT_ERROR = 'GET_INTERN_COMMENT_ERROR';
export const GET_INTERN_COMMENT_RESET = 'GET_INTERN_COMMENT_RESET';