export const DEL_INTERN_POST_INIT = 'DEL_INTERN_POST_INIT';
export const DEL_INTERN_POST_SUCCESS = 'DEL_INTERN_POST_SUCCESS';
export const DEL_INTERN_POST_ERROR = 'DEL_INTERN_POST_ERROR';
export const DEL_INTERN_POST_RESET = 'DEL_INTERN_POST_RESET';

export const ADD_INTERN_POST_INIT = 'ADD_INTERN_POST_INIT';
export const ADD_INTERN_POST_SUCCESS = 'ADD_INTERN_POST_SUCCESS';
export const ADD_INTERN_POST_RESET = 'ADD_INTERN_POST_RESET';
export const ADD_INTERN_POST_ERROR = 'ADD_INTERN_POST_ERROR';

export const SET_INTERN_POST_LIKE_INIT = 'SET_INTERN_POST_LIKE_INIT';
export const SET_INTERN_POST_LIKE_SUCCESS = 'SET_INTERN_POST_LIKE_SUCCESS';
export const SET_INTERN_POST_LIKE_RESET = 'SET_INTERN_POST_LIKE_RESET';
export const SET_INTERN_POST_LIKE_ERROR = 'SET_INTERN_POST_LIKE_ERROR';

export const GET_INTERN_POST_INIT = 'GET_INTERN_POST_INIT';
export const GET_INTERN_POST_SUCCESS = 'GET_INTERN_POST_SUCCESS';
export const GET_INTERN_POST_ERROR = 'GET_INTERN_POST_ERROR';
export const GET_INTERN_POST_RESET = 'GET_INTERN_POST_RESET';