export const DEL_AVANCE_INIT = 'DEL_AVANCE_INIT';
export const DEL_AVANCE_SUCCESS = 'DEL_AVANCE_SUCCESS';
export const DEL_AVANCE_ERROR = 'DEL_AVANCE_ERROR';
export const DEL_AVANCE_RESET = 'DEL_AVANCE_RESET';

export const ADD_AVANCE_INIT = 'ADD_AVANCE_INIT';
export const ADD_AVANCE_SUCCESS = 'ADD_AVANCE_SUCCESS';
export const ADD_AVANCE_RESET = 'ADD_AVANCE_RESET';
export const ADD_AVANCE_ERROR = 'ADD_AVANCE_ERROR';

export const SET_AVANCE_LIKE_INIT = 'SET_AVANCE_LIKE_INIT';
export const SET_AVANCE_LIKE_SUCCESS = 'SET_AVANCE_LIKE_SUCCESS';
export const SET_AVANCE_LIKE_RESET = 'SET_AVANCE_LIKE_RESET';
export const SET_AVANCE_LIKE_ERROR = 'SET_AVANCE_LIKE_ERROR';

export const POSTULATE_AVANCE_INIT = 'POSTULATE_AVANCE_INIT';
export const POSTULATE_AVANCE_SUCCESS = 'POSTULATE_AVANCE_SUCCESS';
export const POSTULATE_AVANCE_ERROR = 'POSTULATE_AVANCE_ERROR';
export const POSTULATE_AVANCE_RESET = 'POSTULATE_AVANCE_RESET';

export const PRE_APROVE_AVANCE_INIT = 'PRE_APROVE_AVANCE_INIT';
export const PRE_APROVE_AVANCE_SUCCESS = 'PRE_APROVE_AVANCE_SUCCESS';
export const PRE_APROVE_AVANCE_RESET = 'PRE_APROVE_AVANCE_RESET';
export const PRE_APROVE_AVANCE_ERROR = 'PRE_APROVE_AVANCE_ERROR';
