export const GET_PROY_INIT = 'GET_PROY_INIT';
export const GET_PROY_SUCCESS = 'GET_PROY_SUCCESS';
export const GET_PROY_ERROR = 'GET_PROY_ERROR';

export const ADD_PROY_INIT = 'ADD_PROY_INIT';
export const ADD_PROY_SUCCESS = 'ADD_PROY_SUCCESS';
export const ADD_PROY_RESET = 'ADD_PROY_RESET';
export const ADD_PROY_ERROR = 'ADD_PROY_ERROR';

export const SET_PROY_LIKE_INIT = 'SET_PROY_LIKE_INIT';
export const SET_PROY_LIKE_SUCCESS = 'SET_PROY_LIKE_SUCCESS';
export const SET_PROY_LIKE_RESET = 'SET_PROY_LIKE_RESET';
export const SET_PROY_LIKE_ERROR = 'SET_PROY_LIKE_ERROR';