export const GET_LOGIN_ACTION_INIT =  'GET_LOGIN_ACTION_INIT'
export const GET_LOGIN_ACTION_ERROR =  'GET_LOGIN_ACTION_ERROR'
export const GET_LOGIN_ACTION_SUCCESS =  'GET_LOGIN_ACTION_SUCCESS'
export const GET_LOGIN_ACTION_RESET =  'GET_LOGIN_ACTION_RESET'

export const CHECK_LOGIN_TOKEN_ACTION_INIT =  'CHECK_LOGIN_TOKEN_ACTION_INIT'
export const CHECK_LOGIN_TOKEN_ACTION_ERROR =  'CHECK_LOGIN_TOKEN_ACTION_ERROR'
export const CHECK_LOGIN_TOKEN_ACTION_SUCCESS =  'CHECK_LOGIN_TOKEN_ACTION_SUCCESS'
export const CHECK_LOGIN_TOKEN_ACTION_RESET =  'CHECK_LOGIN_TOKEN_ACTION_RESET'

export const GET_LOGOUT_ACTION_INIT =  'GET_LOGOUT_ACTION_INIT'
export const GET_LOGOUT_ACTION_ERROR =  'GET_LOGOUT_ACTION_ERROR'
export const GET_LOGOUT_ACTION_SUCCESS =  'GET_LOGOUT_ACTION_SUCCESS'
export const GET_LOGOUT_ACTION_RESET =  'GET_LOGOUT_ACTION_RESET'




