export const DEL_SOL_INIT = 'DEL_SOL_INIT';
export const DEL_SOL_SUCCESS = 'DEL_SOL_SUCCESS';
export const DEL_SOL_ERROR = 'DEL_SOL_ERROR';
export const DEL_SOL_RESET = 'DEL_SOL_RESET';

export const ADD_SOL_INIT = 'ADD_SOL_INIT';
export const ADD_SOL_SUCCESS = 'ADD_SOL_SUCCESS';
export const ADD_SOL_RESET = 'ADD_SOL_RESET';
export const ADD_SOL_ERROR = 'ADD_SOL_ERROR';

export const SET_SOL_LIKE_INIT = 'SET_SOL_LIKE_INIT';
export const SET_SOL_LIKE_SUCCESS = 'SET_SOL_LIKE_SUCCESS';
export const SET_SOL_LIKE_RESET = 'SET_SOL_LIKE_RESET';
export const SET_SOL_LIKE_ERROR = 'SET_SOL_LIKE_ERROR';

export const GET_SOL_INIT = 'GET_SOL_INIT';
export const GET_SOL_SUCCESS = 'GET_SOL_SUCCESS';
export const GET_SOL_ERROR = 'GET_SOL_ERROR';
export const GET_SOL_RESET = 'GET_SOL_RESET';

export const ADD_SOL_USER_INIT = 'ADD_SOL_USER_INIT';
export const ADD_SOL_USER_SUCCESS = 'ADD_SOL_USER_SUCCESS';
export const ADD_SOL_USER_RESET = 'ADD_SOL_USER_RESET';
export const ADD_SOL_USER_ERROR = 'ADD_SOL_USER_ERROR';
